/*
===============================================================================
Short Term LTV Performance Analysis (Cohort by Acquisition Month)
===============================================================================
Purpose:
    - To measure the 120-day-LTV performance overall and of marketing components such as campagins and channels over time.
    - For benchmarking and identifying high-performing entities.
    - To track monthly 2024 trends and growth.

Limitations:
    - Calculation of full LTV is not possible, because the datasets only consist of data across a 4-month span. 
    - Therefor 120-day-LTV will be determined,

SQL Functions Used:
    - LEFT JOIN
    - SUM()
    - COUNT()

Queries: 
    1) Revenue-Based LTV (over 120 days)
    2) LTV:CAC ratio (over 120 days) 
    3) Cohort Anlaysis by Acquistion Month with LTV, LTV:CAC ratio and ROI
    4) Cohort Anlaysis by Acquistion Month and Acquisition Channel with LTV, LTV:CAC ratio and ROI
    5) Cohort Anlaysis by Acquistion Month and Aquisition Campaign with LTV, LTV:CAC ratio and ROI
===============================================================================
*/
USE marketing_dw; 
GO
/*
===============================================================================
1) Revenue-Based LTV 
===============================================================================
Revenue by all users
*/
SELECT 
    SUM(revenue)/(SELECT COUNT(*) FROM gold.dim_user) AS ltv_120_days
FROM gold.fact_purchases 
/*
===============================================================================
1) LTV:CAC ratio
===============================================================================
*/
--Acquisition table based on first touch (fact_touchpoints)
DROP VIEW IF EXISTS gold.fact_user_acquisition;
GO

CREATE VIEW gold.fact_user_acquisition AS
WITH first_touch AS (
    SELECT
        user_id,
        touchpoint_time,
        channel AS acquisition_channel,
        campaign_id AS acquisition_campaign,
        ROW_NUMBER() OVER (
            PARTITION BY user_id 
            ORDER BY touchpoint_time ASC
        ) AS rn
    FROM gold.fact_touchpoints
)
SELECT
    user_id,
    touchpoint_time AS acquisition_date,
    acquisition_channel,
    acquisition_campaign
FROM first_touch
WHERE rn = 1;
GO

SELECT 
    (SELECT SUM(revenue)/(SELECT COUNT(*) FROM gold.dim_user) AS ltv_120_days FROM gold.fact_purchases) 
    /
    ((SELECT SUM(spend) FROM gold.fact_spend)/(SELECT COUNT(distinct user_id) FROM gold.fact_user_acquisition)) AS ltv_cac_ratio_120d;
GO
/*
===============================================================================
3) Cohort Anlaysis by Acquistion Month with LTV, LTV:CAC ratio and ROI
===============================================================================
- LTV is calculated per acquisition cohort based on revenue generated by users starting in the acquisition month (month 0) and all following months.
- CAC is calculated using only the ad spend associated with acquisition campaigns.
  For each acquisition month, total spend is divided by the number of newly acquired users
  (unique users whose first recorded touchpoint occurred in that month).
Formulae:
  LTV = (Total revenue generated by the cohort) / (Number of acquired users)
  CAC = (Total acquisition spend in that month) / (Number of acquired users)
Note:
- Limiting spend to acquisition campaigns avoids inflating CAC with non-acquisition spend.
- Using first-touch attribution ensures each user belongs to exactly one acquisition cohort.
*/
DROP VIEW IF EXISTS gold.fact_ltv_cohort 
GO 

CREATE VIEW gold.fact_ltv_cohort AS
WITH revenue AS (
    SELECT 
        DATEFROMPARTS(YEAR(purchase_date), MONTH(purchase_date), 1) AS purchase_month,
        user_id,
        revenue
    FROM gold.fact_purchases
),
acquisitions AS (
    SELECT 
        DATEFROMPARTS(YEAR(acquisition_date), MONTH(acquisition_date), 1) AS acquisition_month,
        user_id
    FROM gold.fact_user_acquisition
),
acquisition_count AS (
    SELECT
        DATEFROMPARTS(YEAR(acquisition_date), MONTH(acquisition_date), 1) AS acquisition_month,
        COUNT(distinct user_id) AS user_count
    FROM gold.fact_user_acquisition
    GROUP BY DATEFROMPARTS(YEAR(acquisition_date), MONTH(acquisition_date), 1)
),
acquisition_spend AS (
    SELECT
        DATEFROMPARTS(YEAR(s.spend_date), MONTH(s.spend_date), 1) AS spend_month,
        SUM(s.spend) AS total_acquisition_spend
    FROM gold.fact_spend s
    WHERE s.campaign_id IN (
        SELECT DISTINCT acquisition_campaign
        FROM gold.fact_user_acquisition
        WHERE acquisition_campaign IS NOT NULL
    )
    GROUP BY DATEFROMPARTS(YEAR(s.spend_date), MONTH(s.spend_date), 1)
),
ltv_metrics AS (
    SELECT
        a.acquisition_month, 
        r.purchase_month,
        DATEDIFF(MONTH, a.acquisition_month, r.purchase_month) AS month_number,
        SUM(r.revenue) AS total_revenue,
        COUNT(distinct a.user_id) AS users_in_cohort,
        SUM(r.revenue)*1.0 / COUNT(distinct a.user_id) AS ltv
    FROM acquisitions a 
    LEFT JOIN revenue r 
        ON a.user_id = r.user_id 
        AND a.acquisition_month <= r.purchase_month  
    GROUP BY 
        a.acquisition_month, 
        r.purchase_month, 
        DATEDIFF(MONTH, a.acquisition_month, r.purchase_month)
),
cac AS (
    SELECT
        a.acquisition_month,
        s.total_acquisition_spend * 1.0 / a.user_count AS cac
    FROM acquisition_count a
    LEFT JOIN acquisition_spend s
        ON a.acquisition_month = s.spend_month
)

SELECT
    l.*,
    c.cac,
    l.ltv / c.cac AS ltv_cac_ratio, 
    (ltv - cac) / NULLIF(cac, 0) AS roi
FROM ltv_metrics l
LEFT JOIN cac c 
    ON l.acquisition_month = c.acquisition_month 
WHERE l.purchase_month IS NOT NULL;
GO

SELECT * 
FROM gold.fact_ltv_cohort 
ORDER BY acquisition_month, month_number;
GO
 
/*
===============================================================================
4) Cohort Anlaysis by Acquisition Channel with LTV, LTV:CAC ratio and ROI
===============================================================================
*/
DROP VIEW IF EXISTS gold.fact_ltv_cohort_channel 
GO 

CREATE VIEW gold.fact_ltv_cohort_channel AS
WITH revenue AS (
    SELECT 
        DATEFROMPARTS(YEAR(purchase_date), MONTH(purchase_date), 1) AS purchase_month,
        user_id,
        revenue, 
        acquisition_channel
    FROM gold.fact_purchases
),
acquisitions AS (
    SELECT 
        DATEFROMPARTS(YEAR(acquisition_date), MONTH(acquisition_date), 1) AS acquisition_month,
        user_id,
        acquisition_channel
    FROM gold.fact_user_acquisition
),
acquisition_count AS (
    SELECT
        DATEFROMPARTS(YEAR(acquisition_date), MONTH(acquisition_date), 1) AS acquisition_month,
        acquisition_channel,
        COUNT(distinct user_id) AS user_count
    FROM gold.fact_user_acquisition
    GROUP BY DATEFROMPARTS(YEAR(acquisition_date), MONTH(acquisition_date), 1), acquisition_channel
),
acquisition_spend AS (
    SELECT
        DATEFROMPARTS(YEAR(s.spend_date), MONTH(s.spend_date), 1) AS spend_month,
        channel,
        SUM(s.spend) AS total_acquisition_spend
    FROM gold.fact_spend s
    WHERE s.campaign_id IN (
        SELECT DISTINCT acquisition_campaign
        FROM gold.fact_user_acquisition
        WHERE acquisition_campaign IS NOT NULL
    )
    AND s.channel IN (
        SELECT DISTINCT acquisition_channel 
        FROM gold.fact_user_acquisition 
        WHERE acquisition_channel IS NOT NULL
    )
    GROUP BY DATEFROMPARTS(YEAR(s.spend_date), MONTH(s.spend_date), 1), channel
),
ltv_metrics AS (
    SELECT
        a.acquisition_month, 
        r.purchase_month,
        DATEDIFF(MONTH, a.acquisition_month, r.purchase_month) AS month_number,
        a.acquisition_channel,
        SUM(r.revenue) AS total_revenue,
        COUNT(distinct a.user_id) AS users_in_cohort,
        SUM(r.revenue)*1.0 / COUNT(distinct a.user_id) AS ltv
    FROM acquisitions a 
    LEFT JOIN revenue r 
        ON a.user_id = r.user_id
        AND a.acquisition_month <= r.purchase_month  
    GROUP BY 
        a.acquisition_month, 
        r.purchase_month, 
        DATEDIFF(MONTH, a.acquisition_month, r.purchase_month),
        a.acquisition_channel
),
cac AS (
    SELECT
        a.acquisition_month,
        a.acquisition_channel,
        s.total_acquisition_spend * 1.0 / a.user_count AS cac
    FROM acquisition_count a
    LEFT JOIN acquisition_spend s
        ON a.acquisition_month = s.spend_month
        AND a.acquisition_channel = s.channel
)

SELECT
    l.*,
    c.cac,
    l.ltv / c.cac AS ltv_cac_ratio, 
    (ltv - cac) / NULLIF(cac, 0) AS roi
FROM ltv_metrics l
LEFT JOIN cac c 
    ON l.acquisition_month = c.acquisition_month
    AND l.acquisition_channel = c.acquisition_channel
WHERE l.purchase_month IS NOT NULL;
GO 

SELECT * 
FROM gold.fact_ltv_cohort_channel
ORDER BY acquisition_channel, acquisition_month, month_number;
GO

 
/*
===============================================================================
5) Cohort Anlaysis by Acquisition Campaign with LTV, LTV:CAC ratio and ROI
===============================================================================
Some acquisition-month cohorts show unusually high LTV:CAC ratios and unsually high ROIs.
This occurs when CAC is extremely low due to limited or missing spend
recorded for the acquisition campaign in that month.
*/
DROP VIEW IF EXISTS gold.fact_ltv_cohort_campaign 
GO 

CREATE VIEW gold.fact_ltv_cohort_campaign AS
WITH revenue AS (
    SELECT 
        DATEFROMPARTS(YEAR(purchase_date), MONTH(purchase_date), 1) AS purchase_month,
        user_id,
        revenue, 
        acquisition_campaign
    FROM gold.fact_purchases
),
acquisitions AS (
    SELECT 
        DATEFROMPARTS(YEAR(acquisition_date), MONTH(acquisition_date), 1) AS acquisition_month,
        user_id,
        acquisition_campaign
    FROM gold.fact_user_acquisition
),
acquisition_count AS (
    SELECT
        DATEFROMPARTS(YEAR(acquisition_date), MONTH(acquisition_date), 1) AS acquisition_month,
        acquisition_campaign,
        COUNT(distinct user_id) AS user_count
    FROM gold.fact_user_acquisition
    GROUP BY DATEFROMPARTS(YEAR(acquisition_date), MONTH(acquisition_date), 1), acquisition_campaign
),
acquisition_spend AS (
    SELECT
        DATEFROMPARTS(YEAR(s.spend_date), MONTH(s.spend_date), 1) AS spend_month,
        campaign_id,
        SUM(s.spend) AS total_acquisition_spend
    FROM gold.fact_spend s
    WHERE s.campaign_id IN (
        SELECT DISTINCT acquisition_campaign
        FROM gold.fact_user_acquisition
        WHERE acquisition_campaign IS NOT NULL
    )
    GROUP BY DATEFROMPARTS(YEAR(s.spend_date), MONTH(s.spend_date), 1), campaign_id
),
ltv_metrics AS (
    SELECT
        a.acquisition_month, 
        r.purchase_month,
        DATEDIFF(MONTH, a.acquisition_month, r.purchase_month) AS month_number,
        a.acquisition_campaign,
        c.campaign_name,
        SUM(r.revenue) AS total_revenue,
        COUNT(distinct a.user_id) AS users_in_cohort,
        SUM(r.revenue)*1.0 / COUNT(distinct a.user_id) AS ltv
    FROM acquisitions a 
    LEFT JOIN revenue r 
        ON a.user_id = r.user_id
        AND a.acquisition_month <= r.purchase_month 
    LEFT JOIN gold.dim_campaign c 
    ON a.acquisition_campaign = c.campaign_id 
    GROUP BY 
        a.acquisition_month, 
        r.purchase_month, 
        DATEDIFF(MONTH, a.acquisition_month, r.purchase_month),
        a.acquisition_campaign,
        c.campaign_name
),
cac AS (
    SELECT
        a.acquisition_month,
        a.acquisition_campaign,
        s.total_acquisition_spend * 1.0 / a.user_count AS cac
    FROM acquisition_count a
    LEFT JOIN acquisition_spend s
        ON a.acquisition_month = s.spend_month
        AND a.acquisition_campaign = s.campaign_id
)

SELECT
    l.*,
    c.cac,
    l.ltv / c.cac AS ltv_cac_ratio, 
    (ltv - cac) / NULLIF(cac, 0) AS roi
FROM ltv_metrics l
LEFT JOIN cac c 
    ON l.acquisition_month = c.acquisition_month
    AND l.acquisition_campaign = c.acquisition_campaign
WHERE l.purchase_month IS NOT NULL; 
GO 

SELECT * 
FROM gold.fact_ltv_cohort_campaign
ORDER BY acquisition_campaign, acquisition_month, month_number;
GO









































